apiVersion: v1
kind: Service
metadata:
  name: imagestore
  labels:
    app: imagestore
spec:
  selector:
    app: imagestore
  ports:
  - port: 80 
    targetPort: 8010
    # name: imagestore
  type: LoadBalancer
