apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: imagestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagestore
  serviceName: "imagestorage"
  template:
    metadata:
      labels:
        app: imagestore
    spec:
      securityContext:
        runAsUser: 1000
        # runAsGroup: 1000
        fsGroup: 1000

      containers:
      - name: imagestore
        image: alexandrakarlsson/imagestore
        ports:
        - containerPort: 8010
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 400Mi

        volumeMounts:
        - name: imagestore
          mountPath: /home/node/app/images  
        - name: imagebackup
          mountPath: /home/node/app/backup  
            
  volumeClaimTemplates:
  - metadata:
      name: imagestore
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: imagebackup
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 1Gi


        # env:
        # - name: SQL_HOST
        #   value: "tastebudsmysql"  
        # - name: SQL_USER
        #   value: "root"
        # - name: SQL_PASSWORD
        #   value: "example"
        # - name: SQL_DATABASE
        #   value: "tastebuds" 
