apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-backup
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: tastebuds-storage-secret
    shareName: tastebudsbackup
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - mfsymlinks
    - nobrl
