apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: imagestore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imagestore
  serviceName: "imagestorage"
  template:
    metadata:
      labels:
        app: imagestore
    spec:
      containers:
      - name: imagestore
        image: alexandrakarlsson/imagestore
        env:
        - name: SQL_HOST
          value: "tastebudsmysql"  
        - name: SQL_USER
          value: "root"
        - name: SQL_PASSWORD
          value: "example"
        - name: SQL_DATABASE
          value: "tastebuds" 
        ports:
        - containerPort: 8010
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 400Mi

        volumeMounts:
        - name: imagestore
          mountPath: /home/node/app/images  
        - name: imagebackup
          mountPath: /home/node/app/backup  
            
      volumes:
      - name: imagestore
        persistentVolumeClaim:
          claimName: imagestore-azure-file 
      - name: imagebackup
        persistentVolumeClaim:
          claimName: imagebackup-azure-file 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagestore-azure-file
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagebackup-azure-file
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi